### ISSUE TITLE
安卓崩溃

### ISSUE THREAD

**Issue by tanjwGit** [bashen1/react-native-mbaichuan#11]
我收到了如下的线上崩溃信息：
```
java.lang.NullPointerException: Attempt to invoke virtual method &#39;android.app.Application android.app.Activity.getApplication()&#39; on a null object reference
	at com.maochunjie.mbaichuan.RNReactNativeMbaichuanModule.initSDK(RNReactNativeMbaichuanModule.java:76)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:219)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by bashen1** [comment]
传入的东西非法，一般可能由于链接中存在空格，或者是非正常的链接。这个是百川那边报错了，与模块无关，需要在传入参数的时候判断参数的合法性

**Comment by bashen1** [comment]
可以尝试升到最新模块版本
